Move galaxy deps into the requirements file
ansible-community/molecule-kubevirt pull request #4
Opened 2021-01-22 14:08 UTC by LeoColomb

Best practice to avoid deps mismatches, and where version and source can be specified easily.

https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#install-multiple-collections-with-a-requirements-file

2021-01-22 14:42 UTC, LeoColomb commented
@jseguillon 

  - community.crypto
  - community.kubernetes

Are they actually used? I don't any reference.

2021-01-24 14:50 UTC, jseguillon commented
Hi Leo ! Thanks for the PR. 

I'm getting into trouble for validating this change because I can't checkout your banch locally. 

Attaching "strange" screenshot showing I can't access your fork 

![image](https://user-images.githubusercontent.com/1395266/105633967-e875c800-5e5b-11eb-8aa8-7e44bf1a27d2.png)

2021-01-24 14:51 UTC, jseguillon commented
![Capture](https://user-images.githubusercontent.com/1395266/105633985-02170f80-5e5c-11eb-887a-d31ee3cfa2ec.PNG)

2021-01-24 15:19 UTC, LeoColomb commented
@jseguillon Indeed, I've deleted my repository. But you can always fetch a PR head by doing the following:

```shell
git fetch origin refs/pull/4/head:pr/4
git checkout pr/4
```

(where 4 is the PR number and `pr/4` a local branch name of your choice)

2021-01-24 16:38 UTC, jseguillon commented
wow thanks for the hint ! exactly what I was looking for 👍

2021-01-24 17:02 UTC, jseguillon requested changes

2021-01-24 17:02 UTC, jseguillon commented on README.rst
> -- ansible-galaxy collection install community.general
I'm not sure about this one : since people using the driver should not clone the repo but only `pip install` I think doc should still refer to explicit dependencies ? 

Or maybe the python code of the driver may install those deps ? I'll take a look about that.

2021-01-24 17:36 UTC, jseguillon commented on README.rst
> -- ansible-galaxy collection install community.general
also if keeping in doc : must changes community.kubernetes.git to community.kubernetes since its a typo

2021-01-26 16:39 UTC, LeoColomb commented on README.rst
> -- ansible-galaxy collection install community.general
@jseguillon Step by step:
1. I don't see any actual usage of community.crypto and community.kubernetes. Are they actually used? 
  If not, that simplify the question a lot.
2. Are are the python dependencies excepted to be installed currently? I see here few are added manually. If they are required, why not listed on the README?
  https://github.com/jseguillon/molecule-kubevirt/blob/9761180e1c1f479bd32885f021651f0f7ac632dc/tools/Dockerfile#L6

3. Automated way to install dependencies is often much better than expectations on users and maintainers taking care of the documented list.

2021-01-26 16:47 UTC, jseguillon commented on README.rst
> -- ansible-galaxy collection install community.general
1. Crypto is required for creating ssh-key. But this one may be the easier to remove : there should be a way for doing this in the Python part of the driver. 

2. Python deps are well installed via the requirements : I tested it manually => openshift comes when pip install molecule-kubevirt. Pretty sure this could be removed in the Dockerfile (plus jsmeshpath is no more required....) 

3. Sure ! I would also love if we could do something like `ansible-galaxy install https://raw.gitlab/.../molecule-kubevirt/.../requirements ` but did not succeed :/ (nor with `curl https://raw.gitlab/.../molecule-kubevirt/.../requirements |ansible-galaxy install - `)

2021-10-10 17:03 UTC, closed without merging